FROM php:7.4-apache

# Habilitar extensiones necesarias de PHP
RUN docker-php-ext-install mysqli

# Copiar configuración personalizada de Apache (si es necesario)
# COPY my-apache-config.conf /etc/apache2/sites-available/000-default.conf

# Habilitar módulos de Apache (si es necesario)
# RUN a2enmod rewrite
